#! /usr/bin/env python

import urllib
import urllib2
import sys

#Make sure the name of the file is same as the problem number, e.g : 1234.cpp

content = open(sys.argv[1], 'r').read()

cnf = open(sys.argv[3], 'r')

userid = cnf.readline();
userid = userid.split('\n',1);

#print userid[0]

languageid = cnf.readline();
languageid = languageid.split('\n',1)

#print languageid[0]

data = {
        "Action" : "submit",
        "SpaceID" : "1",
        "JudgeID" : userid[0],	# your judgeID
        "Language" : languageid[0],	# your language number
        "ProblemNum" : sys.argv[2],
        "Source" : content
       }

encoded_data = urllib.urlencode(data)
content = urllib2.urlopen("http://acm.timus.ru/submit.aspx?space=1",
        encoded_data)
print content.readlines()